package net.phyloviz.loadmlst.wizard;

import java.awt.Font;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import net.phyloviz.loadmlst.io.XMLParser;

public final class LoadMLSTVisualPanel1 extends JPanel {

	private DefaultComboBoxModel datasetListModel;

	/** Creates new form LoadMLSTVisualPanel1 */
	public LoadMLSTVisualPanel1() {

		datasetListModel = new DefaultComboBoxModel();

		initComponents();
		updateKeyList();

		try {
			URL url = LoadMLSTVisualPanel1.class.getResource("LoadMLSTVisualPanel1.html");
			jEditorPane1.setEditorKit(new HTMLEditorKit());
			jEditorPane1.setPage(url);
			Font font = UIManager.getFont("Label.font");
			String bodyRule = "body { font-family: " + font.getFamily() + "; "
					+ "font-size: " + font.getSize() + "pt; width: " + jEditorPane1.getSize().width + "px;}";
			((HTMLDocument) jEditorPane1.getDocument()).getStyleSheet().addRule(bodyRule);
		} catch (IOException e) {
			Logger.getLogger(LoadMLSTVisualPanel1.class.getName()).log(Level.WARNING,
					e.getLocalizedMessage());
		}
	}

	private void updateKeyList() {
		datasetListModel.removeAllElements();
		XMLParser.getParser().reset();
		ArrayList<String[]> alDatabases = XMLParser.getParser().getDatabaseList();
		if (alDatabases == null || alDatabases.isEmpty()) {
			datasetListModel.addElement(org.openide.util.NbBundle.getMessage(
					LoadMLSTVisualPanel1.class, "Connection.offline"));
			jComboBox1.setEnabled(false);
		} else {
			for (int i = 0; i < alDatabases.size(); i++) {
				String[] sa = alDatabases.get(i);
				datasetListModel.addElement(sa[1] + " - " + sa[0]);
			}
			jComboBox1.setEnabled(true);
		}
	}

	@Override
	public String getName() {
		return "Database";
	}

	public String getDatasetName() {
		return jTextField1.getText();
	}

	public int getSelectedIndex() {
		return jComboBox1.getSelectedIndex();
	}

	public String getSelectedName() {
		int i = jComboBox1.getSelectedIndex();
		if (i < 0) {
			return "";
		}
		return XMLParser.getParser().getDatabaseList().get(i)[0];
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jEditorPane1 = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 0, 8));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LoadMLSTVisualPanel1.class, "LoadMLSTVisualPanel1.jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(LoadMLSTVisualPanel1.class, "LoadMLSTVisualPanel1.jLabel2.text")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 0, 8));

        jTextField1.setText(org.openide.util.NbBundle.getMessage(LoadMLSTVisualPanel1.class, "LoadMLSTVisualPanel1.jTextField1.text")); // NOI18N
        jPanel4.add(jTextField1);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jComboBox1.setModel(datasetListModel);
        jPanel1.add(jComboBox1, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(LoadMLSTVisualPanel1.class, "LoadMLSTVisualPanel1.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jEditorPane1.setBackground(jPanel2.getBackground());
        jEditorPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jEditorPane1.setEditable(false);
        jEditorPane1.setMaximumSize(new java.awt.Dimension(200, 200));
        add(jEditorPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	updateKeyList();
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
