package net.phyloviz.synthdata.wizard;

import java.awt.Font;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.io.StringReader;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;
import net.phyloviz.synthdata.simul.Simulator;

public final class GenDatasetVisualPanel3 extends JPanel {

	/** Creates new form GenDatasetVisualPanel3 */
	public GenDatasetVisualPanel3() {

		initComponents();

		try {
			URL url = GenDatasetVisualPanel3.class.getResource("GenDatasetVisualPanel3.html");
			jEditorPane1.setEditorKit(new HTMLEditorKit());
			jEditorPane1.setPage(url);
			Font font = UIManager.getFont("Label.font");
			String bodyRule = "body { font-family: " + font.getFamily() + "; "
					+ "font-size: " + font.getSize() + "pt; width: " + jEditorPane1.getSize().width + "px;}";
			((HTMLDocument) jEditorPane1.getDocument()).getStyleSheet().addRule(bodyRule);
		} catch (IOException e) {
			Logger.getLogger(GenDatasetVisualPanel3.class.getName()).log(Level.WARNING,
					e.getLocalizedMessage());
		}
	}

	@Override
	public String getName() {
		return "Simulation";
	}

	public void initSimulator(String gensize, String gensampled, String popsize,
			String pfsize, String mut, String rec, String seed) {
		generations = Integer.parseInt(gensize);
		jLabel8.setText(gensampled + "/" + gensize);
		jLabel9.setText(popsize);
		jLabel10.setText(pfsize);
		jLabel11.setText(rec + "/" + mut);
		jLabel12.setText(seed);
		simulator = new Simulator(generations, Integer.parseInt(gensampled),
				Integer.parseInt(popsize), Integer.parseInt(pfsize),
				Integer.parseInt(mut), Integer.parseInt(rec),
				Integer.parseInt(seed));
		jToggleButton1.setEnabled(true);
		jToggleButton1.setSelected(false);
		jProgressBar1.setString("0%");
//		System.out.println("jprogress = 0%");
	}

	public boolean isSimulationFinished() {
		return bSim;
	}
	
	public StringReader getDataset() {
		if (!bSim) {
			return null;
		}
		return new StringReader(simulator.writeLastPopGenerations());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jEditorPane1 = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(6, 0, 0, 8));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel3.text")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel3);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel4.text")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel4);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel5.text")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel5);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel7.text")); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel7);

        org.openide.awt.Mnemonics.setLocalizedText(jToggleButton1, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jToggleButton1.text")); // NOI18N
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton1);

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.GridLayout(6, 0, 0, 8));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel8.text")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel4.add(jLabel8);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel9.text")); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel4.add(jLabel9);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel10.text")); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel4.add(jLabel10);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel11.text")); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel4.add(jLabel11);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel3.class, "GenDatasetVisualPanel3.jLabel12.text")); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel4.add(jLabel12);

        jProgressBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel4.add(jProgressBar1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jEditorPane1.setBackground(jPanel2.getBackground());
        jEditorPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jEditorPane1.setEditable(false);
        jEditorPane1.setMaximumSize(new java.awt.Dimension(200, 200));
        add(jEditorPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
	JToggleButton tb = (JToggleButton) evt.getSource();
	if (tb.isSelected()) {
		jProgressBar1.setString(null);
//		System.out.println("jprogress = null");
		task = new Task();
		task.addPropertyChangeListener(new PropertyChangeListener() {

			@Override
			public void propertyChange(PropertyChangeEvent pce) {
				if ("progress" == pce.getPropertyName()) {
					int progress = (Integer) pce.getNewValue();
					jProgressBar1.setValue(progress);
				}
			}
		});
		task.execute();
	} else {
		task.cancel(true);
	}
}//GEN-LAST:event_jToggleButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
	private Task task;
	private boolean bSim;
	private Simulator simulator;
	private int generations;

	class Task extends SwingWorker<Void, Void> {

		@Override
		public Void doInBackground() {

			for (int i = 0; i < generations; i++) {
				if (isCancelled()) {
					bSim = false;
					jProgressBar1.setString("Simulation canceled!");
					return null;
				}
				simulator.runOneStep();
				int percent = i * 100 / generations;
				setProgress(percent);
				jProgressBar1.setString("Simulating... generation " +
						i + " of " + generations + " (" + percent + " %)");
			}
//			System.out.println("Cycle generations end.");
			jProgressBar1.setValue(100);
			jToggleButton1.setEnabled(false);
			jProgressBar1.setString("Simulation completed!");
			bSim = true;
			return null;
			//TODO: System.out.println(simulator.dumpLastPopSTs());
		}

		@Override
		public void done() {
			setCursor(null); //turn off the wait cursor
		}
	}
}
