/*-
 * Copyright (c) 2016, PHYLOViZ Team <phyloviz@gmail.com>
 * All rights reserved.
 * 
 * This file is part of PHYLOViZ <http://www.phyloviz.net/>.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package net.phyloviz.synthdata.wizard;

import java.awt.Font;
import java.io.IOException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

public final class GenDatasetVisualPanel2 extends JPanel {

    /** Creates new form GenDatasetVisualPanel2 */
    public GenDatasetVisualPanel2() {

	   initComponents();

	   try {
		  URL url = GenDatasetVisualPanel2.class.getResource("GenDatasetVisualPanel2.html");
		  jEditorPane1.setEditorKit(new HTMLEditorKit());
		  jEditorPane1.setPage(url);
		  Font font = UIManager.getFont("Label.font");
		  String bodyRule = "body { font-family: " + font.getFamily() + "; "
				+ "font-size: " + font.getSize() + "pt; width: " + jEditorPane1.getSize().width + "px;}";
		  ((HTMLDocument) jEditorPane1.getDocument()).getStyleSheet().addRule(bodyRule);
	   } catch (IOException e) {
		  Logger.getLogger(GenDatasetVisualPanel2.class.getName()).log(Level.WARNING,
				e.getLocalizedMessage());
	   }

	   //Default parameters
	   jTextField1.setText("1000"); // gensize
	   jTextField2.setText("30"); // gensampled
	   jTextField3.setText("100"); // popsize
	   jTextField4.setText("7"); // pfsize
	   jTextField5.setText("3"); // mut
	   jTextField6.setText("1"); // rec
//		jTextField7.setText((new Random()).nextInt(Integer.MAX_VALUE) + ""); // seed
    }

    public void initSeed() {
	   jTextField7.setText((new Random()).nextInt(Integer.MAX_VALUE / 100) + ""); // seed
    }

    @Override
    public String getName() {
	   return "Parameters";
    }

    public String getGenSize() {
	   return jTextField1.getText();
    }

    public String getGenSampled() {
	   return jTextField2.getText();
    }

    public String getPopSize() {
	   return jTextField3.getText();
    }

    public String getProfileSize() {
	   return jTextField4.getText();
    }

    public String getMutRate() {
	   return jTextField5.getText();
    }

    public String getRecRate() {
	   return jTextField6.getText();
    }

    public String getRandomSeed() {
	   return jTextField7.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jEditorPane1 = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel2.text")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel2);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel3.text")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel3);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel4.text")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel4);

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel1.setMinimumSize(new java.awt.Dimension(650, 85));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 85));
        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel5.text")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel5);

        jTextField1.setText(org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jTextField1.text")); // NOI18N
        jPanel1.add(jTextField1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel9.text")); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel9);

        jTextField2.setText(org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jTextField2.text")); // NOI18N
        jPanel1.add(jTextField2);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel6.text")); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel6);

        jTextField3.setText(org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jTextField3.text")); // NOI18N
        jPanel1.add(jTextField3);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel10.text")); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel10);

        jTextField4.setText(org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jTextField4.text")); // NOI18N
        jPanel1.add(jTextField4);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel7.text")); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel7);

        jTextField5.setText(org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jTextField5.text")); // NOI18N
        jPanel1.add(jTextField5);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel11.text")); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel11);

        jTextField6.setText(org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jTextField6.text")); // NOI18N
        jPanel1.add(jTextField6);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jLabel8.text")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel8);

        jTextField7.setText(org.openide.util.NbBundle.getMessage(GenDatasetVisualPanel2.class, "GenDatasetVisualPanel2.jTextField7.text")); // NOI18N
        jPanel1.add(jTextField7);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jEditorPane1.setBackground(jPanel1.getBackground());
        jEditorPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jEditorPane1.setEditable(false);
        jEditorPane1.setMaximumSize(new java.awt.Dimension(200, 200));
        add(jEditorPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
