package net.phyloviz.stats;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.UIManager;
import javax.swing.table.AbstractTableModel;
import javax.swing.text.html.HTMLDocument;
import net.phyloviz.core.data.DataModel;
import net.phyloviz.core.data.DataSet;
import net.phyloviz.core.data.TypingData;
import net.phyloviz.stats.util.Cache;
import net.phyloviz.stats.util.Compute;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponent;

public class StatisticsPanel extends TopComponent {

    private final AbstractTableModel atm;
    private Cache htmlCache;

    public StatisticsPanel(String name, DataModel dm, DataSet _ds) {
	   super(Lookups.singleton(dm));
	   initComponents();
	   this.setName(name);
	   this.atm = dm.tableModel();

	   jlDatasetSize.setText(dm.size() + "");
	   if (dm instanceof TypingData) {
		  jLabel4.setText("Profile size:");
	   }
	   jLabel5.setText((atm.getColumnCount() - 1) + "");

	   htmlCache = new Cache();

	   jcbColumns.addItem("-- none selected --");
	   for (int c = 0; c < atm.getColumnCount(); c++) {
		  jcbColumns.addItem(atm.getColumnName(c));
	   }
	   jcbColumns.addActionListener(new ActionListener() {

		  @Override
		  public void actionPerformed(ActionEvent ae) {
			 JComboBox jcb = (JComboBox) ae.getSource();
			 int iIndex = (Integer) jcb.getSelectedIndex();
			 if (iIndex > 0) {
				iIndex--;
				if (!htmlCache.hasBody(iIndex)) {
				    Compute comp = new Compute();
				    for (int i = 0; i < atm.getRowCount(); i++) {
					   comp.add((String) atm.getValueAt(i, iIndex));
				    }
				    htmlCache.put(iIndex, comp.getHTML((String) jcb.getSelectedItem()));
				}
				jEditorPane1.setText(htmlCache.getBody(iIndex));
				jEditorPane1.setVisible(true);
				jEditorPane1.setCaretPosition(0);
			 } else {
				jEditorPane1.setText("&nbsp;");
				jEditorPane1.setVisible(false);
			 }
			 jEditorPane1.repaint();
		  }
	   });

	   jEditorPane1.setEditable(false);
	   jEditorPane1.setVisible(true);
	   Font font = UIManager.getFont("Label.font");
	   String bodyRule = "body { font-family: " + font.getFamily() + "; "
			 + "font-size: " + font.getSize() + "pt; width: " + jEditorPane1.getSize().width + "px;}";
	   ((HTMLDocument) jEditorPane1.getDocument()).getStyleSheet().addRule(bodyRule);
    }

    @Override
    protected void componentOpened() {
	   super.componentOpened();
    }

    @Override
    protected void componentClosed() {
	   super.componentClosed();
    }

    @Override
    public int getPersistenceType() {
	   return PERSISTENCE_NEVER;
    }

    @Override
    protected String preferredID() {
	   return "Statistics";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlDatasetSize = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbColumns = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 0, 8));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(StatisticsPanel.class, "StatisticsPanel.jLabel2.text")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel2);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(StatisticsPanel.class, "StatisticsPanel.jLabel4.text")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel4);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(StatisticsPanel.class, "StatisticsPanel.jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel3.add(jLabel1);

        jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setMinimumSize(new java.awt.Dimension(32, 80));
        jPanel4.setPreferredSize(new java.awt.Dimension(32, 80));
        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 0, 8));

        jlDatasetSize.setText(org.openide.util.NbBundle.getMessage(StatisticsPanel.class, "StatisticsPanel.jlDatasetSize.text")); // NOI18N
        jPanel4.add(jlDatasetSize);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(StatisticsPanel.class, "StatisticsPanel.jLabel5.text")); // NOI18N
        jPanel4.add(jLabel5);
        jPanel4.add(jcbColumns);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jEditorPane1.setBackground(jPanel2.getBackground());
        jEditorPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jEditorPane1.setContentType(org.openide.util.NbBundle.getMessage(StatisticsPanel.class, "StatisticsPanel.jEditorPane1.contentType")); // NOI18N
        jEditorPane1.setEditable(false);
        jEditorPane1.setMaximumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setViewportView(jEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setText(org.openide.util.NbBundle.getMessage(StatisticsPanel.class, "StatisticsPanel.jLabel3.text")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
        jPanel1.add(jLabel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbColumns;
    private javax.swing.JLabel jlDatasetSize;
    // End of variables declaration//GEN-END:variables
}