package net.phyloviz.gtview.ui;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import net.phyloviz.core.display.DisplayMenuProvider;
import net.phyloviz.core.display.DisplayOptionsAction;
import net.phyloviz.goeburst.GOeBurstResult;
import org.openide.util.Lookup;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponent;

public class GTPanel extends TopComponent {

	/** Creates new form GTPanel */
	public GTPanel(String name, GOeBurstResult gr) {
		super(Lookups.singleton(gr));
		initComponents();
		this.setName(name);

		this.add(new GraphView(gr));
	}

	@Override
	public void componentActivated() {
		super.componentActivated();
		DisplayMenuProvider dmp = Lookup.getDefault().lookup(DisplayMenuProvider.class);

		ArrayList<Action> al = new ArrayList<Action>();
		al.add(new AbstractAction() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// Nothing...
			}

			@Override
			public String toString() {
				return "Testing...";
			}

		});
		dmp.updateMenu(al);
	}

	@Override
	protected void componentDeactivated() {
		super.componentDeactivated();
		DisplayMenuProvider dmp = Lookup.getDefault().lookup(DisplayMenuProvider.class);
		dmp.updateMenu(null);
	}



	@Override
	public int getPersistenceType() {
		return PERSISTENCE_NEVER;
	}

	@Override
	protected String preferredID() {
		return "GTPanel";
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                setLayout(new java.awt.BorderLayout());
        }// </editor-fold>//GEN-END:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
