package net.phyloviz.goeburst.ui;

import java.util.Date;
import javax.swing.SwingUtilities;
import org.openide.windows.Mode;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

public class OutputPanel extends TopComponent {

	/** Creates new form OutputPanel */
	public OutputPanel() {
		initComponents();
		this.setName("goeBURST Output");
	}

	@Override
	public void open() {
		Mode m = WindowManager.getDefault().findMode("output");
		m.dockInto(this);
		super.open();
	}

	public void append(String text) {
		jTextArea1.append(text);
	}

	public void appendWithDate(String text) {
		jTextArea1.append("[" + new Date() + "]  " + text);
	}

	public void remoteAppend(String text) {
		SwingUtilities.invokeLater(new LocalRunner(this, text));
	}

	public void remoteAppendWithDate(String text) {
		SwingUtilities.invokeLater(new LocalRunner(this, "[" + new Date() + "]  " + text));
	}

	private class LocalRunner implements Runnable {

		private OutputPanel tp;
		private String text;

		public LocalRunner(OutputPanel tp, String text) {
			this.tp = tp;
			this.text = text;
		}

		@Override
		public void run() {
			tp.append(text);
		}

	}

	@Override
	public int getPersistenceType() {
		return PERSISTENCE_NEVER;
	}

	@Override
	protected String preferredID() {
		return "OutputPanel";
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();

                setLayout(new java.awt.BorderLayout());

                jTextArea1.setColumns(20);
                jTextArea1.setEditable(false);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                add(jScrollPane1, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextArea1;
        // End of variables declaration//GEN-END:variables
}
