package net.phyloviz.core.wizard;

import java.util.Collection;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import net.phyloviz.core.util.TypingFactory;
import org.openide.util.Lookup;

public final class LoadDataSetVisualPanel1 extends JPanel {

	private DefaultComboBoxModel typeListModel;

	/** Creates new form LoadDataSetVisualPanel1 */
	public LoadDataSetVisualPanel1() {

		typeListModel = new DefaultComboBoxModel();
		Collection<? extends TypingFactory> result = Lookup.getDefault().lookupAll(TypingFactory.class);
		Iterator<? extends TypingFactory> ir = result.iterator();
		while (ir.hasNext()) {
			typeListModel.addElement(ir.next());
		}

		initComponents();
	}

	@Override
	public String getName() {
		return "Dataset";
	}

	public String getDatasetName() {
		return jTextField1.getText();
	}

	public TypingFactory getTypingFactory() {
		return (TypingFactory) jComboBox1.getSelectedItem();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jTextField1 = new javax.swing.JTextField();
                jComboBox1 = new javax.swing.JComboBox();
                jPanel5 = new javax.swing.JPanel();

                setLayout(new java.awt.BorderLayout());

                jPanel2.setLayout(new java.awt.BorderLayout());

                jPanel3.setLayout(new java.awt.GridLayout(2, 0, 0, 8));

                org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LoadDataSetVisualPanel1.class, "LoadDataSetVisualPanel1.jLabel1.text")); // NOI18N
                jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
                jPanel3.add(jLabel1);

                org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(LoadDataSetVisualPanel1.class, "LoadDataSetVisualPanel1.jLabel2.text")); // NOI18N
                jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 12, 2, 8));
                jPanel3.add(jLabel2);

                jPanel2.add(jPanel3, java.awt.BorderLayout.WEST);

                jPanel4.setLayout(new java.awt.GridLayout(2, 0, 0, 8));

                jTextField1.setText(org.openide.util.NbBundle.getMessage(LoadDataSetVisualPanel1.class, "LoadDataSetVisualPanel1.jTextField1.text")); // NOI18N
                jPanel4.add(jTextField1);

                jComboBox1.setModel(typeListModel);
                jPanel4.add(jComboBox1);

                jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);
                jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

                add(jPanel2, java.awt.BorderLayout.PAGE_START);
        }// </editor-fold>//GEN-END:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JTextField jTextField1;
        // End of variables declaration//GEN-END:variables
}
